n1 = float(input("Digite o primeiro númer: "))
n2 = float(input("Digite o segundo numero: "))
print("-" *30)
print("Soma = ", n1 + n2)
print("Subtração = ", n1 - n2)
print("Multiplicação = ", n1 * n2)
print("Divisão = ", n1 / n2)
print("Quadrado do 1 = ", n1**2)
print("Quadrado do 2 = ", n2**2)
print("-" *30)